<!-- Code generated by Omnitags plugin - BEGIN -->
<?php
if (isset($omnitags_google_search_console_verification_meta) && $omnitags_google_search_console_verification_meta != "") {
    echo $omnitags_google_search_console_verification_meta;
}

if (isset($omnitags_bing_webmaster_tools_verification_meta) && $omnitags_bing_webmaster_tools_verification_meta != "") {
    echo $omnitags_bing_webmaster_tools_verification_meta;
}

if (isset($omnitags_google_analytics_tracking_id) && $omnitags_google_analytics_tracking_id != "") {
echo '<!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id='.$omnitags_google_analytics_tracking_id.'"></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag(\'js\', new Date());gtag(\'config\', \''.$omnitags_google_analytics_tracking_id.'\');</script>';
}

if (isset($omnitags_piwik_url) && $omnitags_piwik_url != "" && isset($omnitags_piwik_site_id) && $omnitags_piwik_site_id != "") {
echo '<!-- Piwik --><link rel="dns-prefetch" href="'.$omnitags_piwik_url.'"><script type=\'text/javascript\'>var _paq = _paq || []; _paq.push([\'trackPageView\']); _paq.push([\'enableLinkTracking\']); (function() {var u=\''.$omnitags_piwik_url.'/\'; _paq.push([\'setTrackerUrl\', u+\'piwik.php\']); _paq.push([\'setSiteId\', \''.$omnitags_piwik_site_id.'\']); var d=document, g=d.createElement(\'script\'), s=d.getElementsByTagName(\'script\')[0]; g.type=\'text/javascript\'; g.async=true; g.defer=true; g.src=u+\'piwik.js\'; s.parentNode.insertBefore(g,s);})();</script><!-- End Piwik Code -->';
}

if (isset($omnitags_custom_tag_1_script) && $omnitags_custom_tag_1_script != "") {
    echo $omnitags_custom_tag_1_script;
}
?>
<!-- Code generated by Omnitags plugin - END -->
